/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsProjectsRouteImport } from './routes/settings.projects'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsExtensionsRouteImport } from './routes/settings.extensions'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsExtensionsSkillsRouteImport } from './routes/settings.extensions.skills'
import { Route as SettingsExtensionsPluginsRouteImport } from './routes/settings.extensions.plugins'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as SettingsProjectsEnvironmentIdProjectIdRouteImport } from './routes/settings.projects.$environmentId.$projectId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsProjectsRoute = SettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExtensionsRoute = SettingsExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExtensionsSkillsRoute =
  SettingsExtensionsSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => SettingsExtensionsRoute,
  } as any)
const SettingsExtensionsPluginsRoute =
  SettingsExtensionsPluginsRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => SettingsExtensionsRoute,
  } as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const SettingsProjectsEnvironmentIdProjectIdRoute =
  SettingsProjectsEnvironmentIdProjectIdRouteImport.update({
    id: '/$environmentId/$projectId',
    path: '/$environmentId/$projectId',
    getParentRoute: () => SettingsProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/extensions': typeof SettingsExtensionsRouteWithChildren
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/projects': typeof SettingsProjectsRouteWithChildren
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/extensions/plugins': typeof SettingsExtensionsPluginsRoute
  '/settings/extensions/skills': typeof SettingsExtensionsSkillsRoute
  '/settings/projects/$environmentId/$projectId': typeof SettingsProjectsEnvironmentIdProjectIdRoute
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/extensions': typeof SettingsExtensionsRouteWithChildren
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/projects': typeof SettingsProjectsRouteWithChildren
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/extensions/plugins': typeof SettingsExtensionsPluginsRoute
  '/settings/extensions/skills': typeof SettingsExtensionsSkillsRoute
  '/settings/projects/$environmentId/$projectId': typeof SettingsProjectsEnvironmentIdProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/extensions': typeof SettingsExtensionsRouteWithChildren
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/projects': typeof SettingsProjectsRouteWithChildren
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/extensions/plugins': typeof SettingsExtensionsPluginsRoute
  '/settings/extensions/skills': typeof SettingsExtensionsSkillsRoute
  '/settings/projects/$environmentId/$projectId': typeof SettingsProjectsEnvironmentIdProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/projects'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/extensions/plugins'
    | '/settings/extensions/skills'
    | '/settings/projects/$environmentId/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/projects'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/extensions/plugins'
    | '/settings/extensions/skills'
    | '/settings/projects/$environmentId/$projectId'
  id:
    | '__root__'
    | '/_chat'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/projects'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/settings/extensions/plugins'
    | '/settings/extensions/skills'
    | '/settings/projects/$environmentId/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/projects': {
      id: '/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof SettingsProjectsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/extensions/skills': {
      id: '/settings/extensions/skills'
      path: '/skills'
      fullPath: '/settings/extensions/skills'
      preLoaderRoute: typeof SettingsExtensionsSkillsRouteImport
      parentRoute: typeof SettingsExtensionsRoute
    }
    '/settings/extensions/plugins': {
      id: '/settings/extensions/plugins'
      path: '/plugins'
      fullPath: '/settings/extensions/plugins'
      preLoaderRoute: typeof SettingsExtensionsPluginsRouteImport
      parentRoute: typeof SettingsExtensionsRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/projects/$environmentId/$projectId': {
      id: '/settings/projects/$environmentId/$projectId'
      path: '/$environmentId/$projectId'
      fullPath: '/settings/projects/$environmentId/$projectId'
      preLoaderRoute: typeof SettingsProjectsEnvironmentIdProjectIdRouteImport
      parentRoute: typeof SettingsProjectsRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsExtensionsRouteChildren {
  SettingsExtensionsPluginsRoute: typeof SettingsExtensionsPluginsRoute
  SettingsExtensionsSkillsRoute: typeof SettingsExtensionsSkillsRoute
}

const SettingsExtensionsRouteChildren: SettingsExtensionsRouteChildren = {
  SettingsExtensionsPluginsRoute: SettingsExtensionsPluginsRoute,
  SettingsExtensionsSkillsRoute: SettingsExtensionsSkillsRoute,
}

const SettingsExtensionsRouteWithChildren =
  SettingsExtensionsRoute._addFileChildren(SettingsExtensionsRouteChildren)

interface SettingsProjectsRouteChildren {
  SettingsProjectsEnvironmentIdProjectIdRoute: typeof SettingsProjectsEnvironmentIdProjectIdRoute
}

const SettingsProjectsRouteChildren: SettingsProjectsRouteChildren = {
  SettingsProjectsEnvironmentIdProjectIdRoute:
    SettingsProjectsEnvironmentIdProjectIdRoute,
}

const SettingsProjectsRouteWithChildren =
  SettingsProjectsRoute._addFileChildren(SettingsProjectsRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRouteWithChildren
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsProjectsRoute: typeof SettingsProjectsRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsExtensionsRoute: SettingsExtensionsRouteWithChildren,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsProjectsRoute: SettingsProjectsRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
